spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concert?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
